SKYOPS-73008
adobe/aio-lib-core-logging pull request #55
Opened 2024-05-22 11:40 UTC by MaciejZurekk

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-24 05:20 UTC, RemoLiechti approved these changes

2024-05-27 04:04 UTC, shazron requested changes
See [our tests](https://github.com/adobe/aio-lib-core-logging/blob/fc4c9b52ad8b0a5449c550a589deee7c2c65237f/test/AioLogger.test.js#L187) for `DEBUG` usage. This is a limitation of our use of the [popular debug npm module](https://www.npmjs.com/package/debug) which has no concept of log levels.

In general, if you use the `debug` log provider (not the default), you will have set `AIO_LOG_LEVEL` as normal, and also set `DEBUG` env var to your module name (which cannot have spaces). For the `winston` log provider, you only set `AIO_LOG_LEVEL`.

e.g in your code:

```javascript
const logger = require('@adobe/aio-lib-core-logging')('MyModuleName', { provider: 'debug' })
logger.info('info')
logger.debug('debug')
```

... to see both logs, you would do:

```sh
AIO_LOG_LEVEL=debug
DEBUG=MyModuleName
```

Yes, we know it is not consistent: https://github.com/adobe/aio-lib-core-logging/issues/6

You can also set the log level to be from whatever config you want, in this case, I set it to another env var:

e.g.

```javascript
const logger = require('@adobe/aio-lib-core-logging')('MyModuleName', { provider: 'debug', level: process.env.FOOBAR })
logger.info('info')
logger.debug('debug')
```

2024-05-27 10:16 UTC, MaciejZurekk commented
I made changes.

2024-05-27 10:41 UTC, shazron approved these changes

2024-05-27 10:42 UTC, merged